### ISSUE TITLE
Изменить роут reviews. Создать get запрос для выборки среднеарифметического поля rating для тикета 192 на фронте

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_back#100]
Задача
Изменить роут reviews. Создать get запрос для выборки среднеарифметического поля rating (модель Review) по productId
Мотивация
Изменить роут reviews для тикета 192
Критерии приемки
Работа get запроса без ошибок при тестировании

Планируемое время работы
30 минут

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 50 минут
