### ISSUE TITLE
Реализовать пагинацию для отправки Accommodations(для тикета-фронт 233)

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#122]
Задача:
Реализовать пагинацию для отправки Accommodations

Мотивация:
Клиент будет получать данные по частям, для облегчения работы приложения

Критерии приемки:
Данные отправляются на клиент частями

Планируемое время работы:
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 3  часа
