### ISSUE TITLE
Обновить порты проекта

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_back#41]
Задача:
Обновить порты локального запуска проекта на 8085

Мотивация:
У большинства участников двухзначные порты заняты системой

Предполагаемое время выполнения:
30 минут

**Comment by mkonevgit** [comment]
Выявленные проблемы и что сделано.
Столкнулся с проблемой запуска фикстур на сервере деплоймента. 
Несколько тестов выявило, что фикстуры отрабатывали с ошибкой в среде выполнения докер-контейнера бакенда при запуске из докер-файла контейнера командой RUN node fixtures.js. Если же запускать фикстуру из среды выполнения выделенного севера то в эту среду нужно установить полноценные nodejs, mongodb и развернуть там полноценное бакенд-приложение.

Путем нескольких дополнительных тестов из положения вышел следующим образом.

1. Вынес подписчик db.once('open' , async () => {... из fixtures.js на событие "open" mongoDB в отдельный файл fixtures-code.js. Создал там и экспортировал функцию fixApply, которая выполняет эту подписку.
2. Создал дополнительную фикстуру fixtures-deploy.js для запуска в среде выполнения докер-контейнера бакенда с соотв. параметрами соединения с mongoDB. Таким образом функцию fixApply может вызывать как файл fixtures.js, который выполняется в среде разработки так и файл fixtures-deploy.js, каждый с соотв. параметрами соединения с mongoDB. Сам же код фикстуры по мере развития проекта можно редактировать в файле fixtures-code.js.
3. Изменил файл index.js
3.1 Добавил условие 
if (MONGO_HOSTNAME) {
   url = `mongodb://${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_DB}`;
   portVar = PORT;
} else {
   url = config.getDbUrl();
   portVar = 8000;
}
которое меняет параметры соединения с базой и порт запуска бакенда в зависимости от состояния переменной окружения $MONGO_HOSTNAME. Эта переменная принимает значения только при запуске index.js в среде выполнения докер-контейнера (условие MONGO_HOSTNAME ?? localhost не работает).
3.2 Добавил условие   if (MONGO_HOSTNAME) fixApply(mongoose.connection);. Подписчик срабатывает только в докер-контейнере
3.3 Убрал await от вызова mongoose.connect(... поскольку подписчик фикстуры fixApply(mongoose.connection); для его запуска при событии "open" mongoDB должен сработать с опережением, перед этим событием, в синхронном режиме. Так работают файлы fixtures.js и fixtures-deploy.js (см.). Кроме того в данном случае await не требуется т.к. после него выполняется код монтирования middleware и запуска прослушивателя бакенда, не зависящий от соединения с базой.
3.4 Файл фикстур в любом случае необходимо запускать в контейнере на сервере, поскольку при деплойменте создается пустая база, поэтому пришлось искать решение

**Comment by mkonevgit** [comment]
4. Решил проблему с ошибкой фронта при запросе данных после перезапуска скрипта деплоймента на уже существующей базе mongoDB. В скрипте нужно выполнять команду
sudo rm -Rf /var/lib/docker/volumes/glamping_back_dbdata/_data/_data чистящую каталог тома базы mongoDB, работающей в докер контейнере. При перезапуске скрипта деплоймента создаются новые файлы, которые конфликтуют с файлами базы удаленного контейнера из-за чего она приходила в неработоспособное состояние.
5. Из-за большого количество тестов скрипта деплоймента и поиска информации по проблеме выполнение тикета заняло 7-8 ч. Сейчас имеем работоспособный скрипт + протестированные настройки докер и правки в коде на фронте и бакенде как в условиях разработки так и в среде выполнения докер

**Comment by mkonevgit** [comment]
Скрипт деплоймента
rm -Rf ~/projects/glamping_back
rm -Rf ~/projects/glamping_front
git clone git@github.com:13IEZ/glamping_back.git
git clone git@github.com:13IEZ/glamping_front.git
docker stop $(docker ps -q)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
sudo rm -Rf /var/lib/docker/volumes/glamping_back_dbdata/_data/_data
cd ~/projects/glamping_back
docker-compose up -d
cd ~/projects/glamping_front
docker build -t esdp/glamping_front .
docker run -d -it  -p 3001:80/tcp --name glamping_front esdp/glamping_front:latest
