### ISSUE TITLE
Разместить проект на сервере Attractor

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_back#42]
Задача
Разместить docker проекта на сервере Attractor school

Мотивация
Деплой приложения

Критерии приемки
Приложение задеплоино и работает без ошибок

Планируемое время работы
2 часа

**Comment by mkonevgit** [comment]
Что сделано:
1. Установил docker и docker-compose на новый выделенный attractor school сервер
2. Протестировал deployment проекта на новый север

**Comment by mkonevgit** [comment]
Фактическое затраченное время 2 часа
