### ISSUE TITLE
Изменения eslint

### ISSUE THREAD

**Issue by 13IEZ** [13IEZ/glamping_back#45]
Задача
Дополнить файл .eslintrc следующим содержанием:
в выделенную, на скрине, строку добавить 'unix'
![1](https://user-images.githubusercontent.com/70585151/125230065-e0222400-e2f9-11eb-955a-a0605c3c61e7.png)

Мотивация
Линт начнет корректно поддерживать unix системы

Критерии приемки
Выделенная строка дополнена новым содержанием

Планируемое время работы
30 мин

**Comment by pashulia** [comment]
total time 30 min
