### ISSUE TITLE
Создать роут на получение последних 4 modules.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#48]
Задача:
• Создать роут на получение последних 4 modules

План решения:
В папке routes дополнить файл modules.js, в нем прописать роут на получение последних 4 modules

Мотивация:
Позволит отображать на фронте в блоке мини-магазин последнии добавления по модулям.

Критерии приемки:
В папке routes дополнить файл modules.js, в котором прописать указанный роут.

Планируемое время работы
1 часа

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 1 час
