### ISSUE TITLE
Создать роут на получение последних 4 locations.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#49]
Задача:
• Создать роут на получение последних 4 locations

План решения:
В папке routes дополнить файл locations.js, в нем прописать роут на получение последних 4 locations

Мотивация:
Позволит отображать на фронте в блоке мини-локации последнии добавления по локациям.

Критерии приемки:
В папке routes дополнить файл locations.js, в котором прописать указанный роут.

Планируемое время работы
1 часа

**Comment by Dauren3310** [comment]
Фактическое время выполнения: 1 час

**Comment by pashulia** [comment]
Отличная работа!
