### ISSUE TITLE
Добавить модели в фикстуры.

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#50]
Задача:
Добавить еще по одной модели в фикстуры для Location и Module, что-бы на фронте в блоках мини были отображены по четыре карточки.

План решения:
В файле fixtures-code.js дописать еще по по одной модели для Location и Module.

Мотивация:
Позволит отображать на фронте в блоке мини-локации и мини-магазин четыре карточки с данными по локациям и модулям.

Критерии приемки:
В файле fixtures-code.js должны быть по четыре модели.

Планируемое время работы
1 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачен 1 час
