### ISSUE TITLE
Дополнить спецификации в Swagger (модель Module)

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#52]
Задача:
Дополнить спецификации в Swagger (модель Module)

Мотивация
Внести требуемый порядок и иерархию в Swagger для элемента Module

Критерии приемки
Swagger должен определять наименование модели Module, его порядок и содержимое инструменты публикации должны программно анализировать информацию об API и отображать компонент Module в стилизованном интерактивном виде

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 3 часа
