### ISSUE TITLE
Дополнить спецификации в Swagger (модель Location)

### ISSUE THREAD

**Issue by pashulia** [13IEZ/glamping_back#53]
Задача:
Дополнить спецификации в Swagger (модель Location)

Мотивация
Внести требуемый порядок и иерархию в Swagger для элемента Location

Критерии приемки
Swagger должен определять наименование модели Location, его порядок и содержимое,  инструменты публикации должны программно анализировать информацию об API и отображать компонент Location в стилизованном интерактивном виде

Планируемое время работы
2 часа

**Comment by DianaIsseyeva** [comment]
на тикет потрачено 1,5 часа
