### ISSUE TITLE
Реализовать отправку данных с сервера по категориям модулей

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_back#63]
Задача
В modules дополнить get запрос на отправку данных по выбранной категории

Мотивация
Пользователь сможет получить модули по конкретной категории

Критерии приемки
Get запрос содержит логику отправки данных в соответствии с выбранной категорией.

**Comment by 13IEZ** [comment]
Как мы можем увидеть, у нас 3 исполнителя, потому что тикеты с фронта, которые за нами закреплены связаны с логикой отправки данных.

Вести разработку будет 1 человек (на ваш выбор Даурен либо Павел) но нам в любом случае надо будет это делать сообща. Первым будет тикет Павла, потому что ему приходит первый массив на главную страницу и там же указан первый query параметр page потом уже более глубокая логика Даурена по чему конкретному.
