### ISSUE TITLE
Реализовать отправку модулей по опциям указанным в компоненте StoreSidebar

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_back#64]
Задача
Для modules добавить в get запрос отправку данных в соответствии со следующими критериями отбора:
- по цене
- по вместимости
- по сезонности
- по производителю
- по категории

Мотивация
Пользователь сможет отсортировать данные по своему желанию

Критерии приемки
В modules get запрос содержит логику отправки данных в соответствии с критериями полученными в запросе

**Comment by 13IEZ** [comment]
Как мы можем увидеть, у нас 3 исполнителя, потому что тикеты с фронта, которые за нами закреплены связаны с логикой отправки данных.

Вести разработку будет 1 человек (на ваш выбор Даурен либо Павел) но нам в любом случае надо будет это делать сообща. Первым будет тикет Павла, потому что ему приходит первый массив на главную страницу и там же указан первый query параметр page потом уже более глубокая логика Даурена по чему конкретному.
