### ISSUE TITLE
Реализовать отправку модулей по 15 единиц (связан с тикетом 157 на фронте)

### ISSUE THREAD

**Issue by DianaIsseyeva** [13IEZ/glamping_back#68]
Задача
Реализовать логику отправки модулей по 15 единиц, при нажатии на кнопку пагинации

Мотивация
Клиент не будет загружен получением сразу всех данных, что облегчит работу приложения

Критерии приемки
Сервер отдает на клиент по 15 единиц модулей

Планируемое время: 2 часа

**Comment by pashulia** [comment]
потраченное время 3 часа, так-как начал реализовывать при помощи библиотеки mongoose-pagination но в дальнейшем отказался, нашел более простой способ
