### ISSUE TITLE
Обновить структуру данных, создать роут для тикета 186

### ISSUE THREAD

**Issue by mkonevgit** [13IEZ/glamping_back#94]
Задача
Обновить структуру данных, создать роут для тикета 186
1. Скопировать новые файлы схем Acomod.js и Pich.js и fixtures-code.js в проект
2. Выполнить fixtures-code.js
3. Создать CRUD route accomod для отображения данных на странице глэмпингов (тикет 186 фронт)
Описание структуры запрашиваемых данных на странице см. в тикете 186 фронт
4. Добавить к роуту функционал multer для обновления и удаления файлов поля image в схеме Acomod
5. Для тикета 186 написать get запрос связывающий модели Acomod, Product, Category (в запросе нужны поля title Category и roominess Product)

Мотивация
Создать роут для тикета на фронте

Планируемое время работы
3 часа
Критерии приемки
Нормальная работа роута после тестирования

**Comment by DianaIsseyeva** [comment]
на тикет потрчаено 4 часа
